micronaut:
  application:
    name: se09-user-service
  server:
    port: 8181
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/user-service'
    username: 'postgres'
    password: 'postgres'
    driverClassName: 'org.postgresql.Driver'
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE:2}
jpa:
  default:
    packages-to-scan:
      - 'se09.user.service'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
#        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations

hydra:
  url: "http://localhost:4445"
