micronaut:
  application:
    externalhost: ${EXTERNAL_HOSTNAME}
    name: se09-user-service
  server:
    port: ${PORT:8080}
    netty:
      log-level: DEBUG
datasources:
  default:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    maximumPoolSize: 3
    minimumIdle: 2
jpa:
  default:
    packages-to-scan:
      - 'se09.user.service'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
#        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations

hydra:
  url:
    admin: ${HYDRA_URL_ADMIN}
logging:
  level:
    ROOT: DEBUG
  io.micronaut.http.client: INFO
  io.micronaut.http.server: INFO