micronaut:
  application:
    externalhost: ${EXTERNAL_HOSTNAME}
    name: se09-user-service
  server:
    port: ${PORT:8080}
datasources:
  default:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE:2}
jpa:
  default:
    packages-to-scan:
      - 'se09.user.service'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
#        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations

hydra:
  url:
    public: ${HYDRA_URL_PUBLIC}


