version: 2.1
jobs:
  build-and-push:
    context: SE09
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: hengel2810/se09-user-service
      - docker/push:
          image: hengel2810/se09-user-service
orbs:
  docker: circleci/docker@0.5.20
workflows:
  commit:
    jobs:
      - build-and-push