version: 2
jobs:
  build:
    context: SE09
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t hengel2810/se09-user-service:$CIRCLE_BUILD_NUM .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker push hengel2810/se09-user-service:$CIRCLE_BUILD_NUM
#      - run:
#          name: Deploy app to Digital Ocean Server via Docker
#          command: |
#            ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"